main = ".open-next/worker.js"
name = "my-next-app"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
[build]
command = "npm run build"
node_version = "23"